### PR TITLE
Dependency Check

### PR DESCRIPTION
**Pull request by databoose**
Add check for required dependecy for debian/arch based systems. Installs if non-existent.

### CODE REVIEW

**Comment by thrimbor** [comment]
There are countless different distributions and package managers, and it's impractical to support all (or even most).
I'd prefer to keep it simple instead, by better documenting the dependency in the README and maybe a simple check for xsltproc at the top of the build script.
That way we don't have to deal with any distribution-specific behavior or keep track of renamed packages etc.

**Comment by databoose** [comment]
> There are countless different distributions and package managers, and it's impractical to support all (or even most). I'd prefer to keep it simple instead, by better documenting the dependency in the README and maybe a simple check for xsltproc at the top of the build script. That way we don't have to deal with any distribution-specific behavior or keep track of renamed packages etc.

I have changed the script to include any arch, or arch-based system (not counting for arch deviation distros like manjaro that do not classify themselves as arch in ID_LIKE).

For clarification on what ID_LIKE is, and what it entails, the documentation can be viewed here : https://www.freedesktop.org/software/systemd/man/latest/os-release.html

I respectfully but fully disagree with this reply for multiple reasons though : 

"There are countless different distributions and package managers, and it's impractical to support all (or even most)."

This is a technically true statement but an extremely misleading one, the grand majority of systems, in this context of desktop users within linux, are based on debian , or if not, than arch, and the grand majority of desktop linux systems, use their respective default package manager, with debian being APT, and arch's being pacman.

For example, linux mint, ubuntu, zorin OS, all of these "based systems" still fully utilize both the full and official package repos for the "root" distros, they just add onto that base, they do not remove from the root of the distro, there is no confliction here except in very obscure distros. (in which this script wouldn't even pick up)

**Just about all of these debian based systems are going to be using APT, and virtually all of these arch/arch based systems are going to be pacman**

With arch, there is actually far less arch-based systems, the most notable coming to mind being endeavourOS, which again fully implements the official arch repo and adding non-conflicting features on top of  that base.

**What this would not cover, at least for now** , is fedora and gentoo systems, however it is very safe to say that most linux users here would be covered on this script even now at this stage.

**Comment by databoose** [comment]
Additionally i'd like to add, that not adding these checks at all is literally just only a negative result and zero positive result, there is no risk or no downside to adding checks for popular linux desktop systems to have this package.

I had to spend an entire day figurig out what the problem was until i had realized i was simply missing this package, i think this would be a great addition that would prevent future users from encountering the same issue i had to.

**Comment by mborgerson** [comment]
I appreciate the thought for convenience, but having a build script invoke the user's package manager to install a dependency seems surprising and unnecessary.

> maybe a simple check for xsltproc at the top of the build script

I agree. Let's simply add a check for the tool.

**Comment by databoose** [comment]
> I appreciate the thought for convenience, but having a build script invoke the user's package manager to install a dependency seems surprising and unnecessary.
> 
> > maybe a simple check for xsltproc at the top of the build script
> 
> I agree. Let's simply add a check for the tool.

Fair enough although the dep would need to be checked for on a per-distro basis, unless regardless of package the library is always stored in the same exact path, which i feel like may be unreliable.

But if most people agree that simply detection of the absecene of this library is a better solution, feel free to edit this code as, quite frankly i am terrible with bash (and i presume obviously this script would want to be kept bash)

**Comment by databoose** [comment]
I will be closing this solution as the concensus seems to be that this is not the right appreach, i will be closing the PR, but i'm open to new ideas regarding this,

**Pull request closed without merging**
